repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^[art.bib|mkdocs]*
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy # type annotations
        exclude: ^docs/
