site_name: !ENV [SITE_NAME, "Anoma Specification"]
site_author: !ENV [SITE_AUTHOR, "Anoma Foundation"]
site_description: !ENV [SITE_DESCRIPTION, "The Anoma Specification is a collection of documents that describe the architecture, design, and implementation of the Anoma Network."]
site_dir: !ENV [SITE_DIR, site]
site_url: !ENV [SITE_URL, 'https://specs.anoma.net/']
site_version: !ENV [SITE_VERSION, "v0.1.1"]
copyright: !ENV [COPYRIGHT, "&copy; 2024 <a href=\"https://anoma.net\">Anoma Foundation</a>"]
use_directory_urls: false
nav:
  - Home: index.md
  - Changelog: ./changelog.md
  - Protocol Architecture:
      - ./arch/index.md
      - System Architecture:
          - ./arch/system/index.md
          - Identity Architecture: ./arch/system/identity/identity.juvix.md
          - State Architecture:
              - Resource Machine:
                  - ./arch/system/state/resource_machine/index.md
                  - Primitive interfaces:
                      - ./arch/system/state/resource_machine/primitive_interfaces/index.md
                      - Set: 
                          - Set interface: ./arch/system/state/resource_machine/primitive_interfaces/set.md
                          - Ordered set: ./arch/system/state/resource_machine/primitive_interfaces/ordered_set.md
                      - Map: ./arch/system/state/resource_machine/primitive_interfaces/map.md
                      - Fixed size type:
                          - Interface: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/fixed_size_type.md
                          - Arithmetic: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/arithmetic.md
                          - Hash: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/hash.md
                          - Delta hash: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/delta_hash.md
                      - Proving system:
                          - ./arch/system/state/resource_machine/primitive_interfaces/proving_system/index.md
                          - Definitions: ./arch/system/state/resource_machine/primitive_interfaces/proving_system/proving_system_types.md
                          - Delta proving system: ./arch/system/state/resource_machine/primitive_interfaces/proving_system/proving_system_delta.md
                      - Commitment accumulator: ./arch/system/state/resource_machine/primitive_interfaces/commitment_accumulator.md
                      - Nullifier set: ./arch/system/state/resource_machine/primitive_interfaces/nullifier_set.md
                  - Data structures:
                      - ./arch/system/state/resource_machine/data_structures/index.md
                      - Resource:
                          - ./arch/system/state/resource_machine/data_structures/resource/index.md
                          - Computable components:
                              - ./arch/system/state/resource_machine/data_structures/resource/computable_components/introduction.md
                              - Commitment: ./arch/system/state/resource_machine/data_structures/resource/computable_components/resource_commitment.md
                              - Nullifier: ./arch/system/state/resource_machine/data_structures/resource/computable_components/nullifier.md
                              - Kind: ./arch/system/state/resource_machine/data_structures/resource/computable_components/kind.md
                              - Delta: ./arch/system/state/resource_machine/data_structures/resource/computable_components/delta.md
                      - Compliance unit: 
                          - Compliance unit: ./arch/system/state/resource_machine/data_structures/compliance_unit/compliance_unit.md
                          - Compliance proof: ./arch/system/state/resource_machine/data_structures/compliance_unit/compliance_proof.md
                      - Action:
                          - Action: ./arch/system/state/resource_machine/data_structures/action/index.md
                          - Resource logic proof: ./arch/system/state/resource_machine/data_structures/action/resource_logic_proof.md
                      - Transaction: 
                          - Transaction: ./arch/system/state/resource_machine/data_structures/transaction/transaction.md
                          - Delta proof: ./arch/system/state/resource_machine/data_structures/transaction/delta_proof.md
                          - Transaction Function: ./arch/system/state/resource_machine/data_structures/transaction/transaction_function.md
                          - Transaction With Payment: ./arch/system/state/resource_machine/data_structures/transaction/transaction_with_payment.md 

                  - Execution flow: ./arch/system/state/resource_machine/execution_flow/flow.md
                  - Notes:
                      - Roles and requirements: ./arch/system/state/resource_machine/notes/roles_and_requirements.md
                      - Stored data format: ./arch/system/state/resource_machine/notes/storage.md
                      - Function formats:
                          - Transaction function format: ./arch/system/state/resource_machine/notes/function_formats/transaction_function_format.md
                      - Applications: ./arch/system/state/resource_machine/notes/applications.md
      - Node Architecture:
          - ./arch/node/index.md
          - Basic Types:
              - ./arch/node/types/basics.juvix.md
              - Cryptographic Primitives: ./arch/node/types/crypto.juvix.md
              - Identities: ./arch/node/types/identities.juvix.md
              - Messages & Mailboxes: ./arch/node/types/messages.juvix.md
          - Engine Types:
              - ./arch/node/engines/index.md
              - Engine:
                  - ./arch/node/types/engine.juvix.md
                  - Engine Configuration: ./arch/node/types/engine_config.juvix.md
                  - Engine Environment: ./arch/node/types/engine_environment.juvix.md
                  - Engine Behaviour: ./arch/node/types/engine_behaviour.juvix.md
              - Anoma:
                  - Anoma Message: ./arch/node/types/anoma_message.juvix.md
                  - Anoma Configuration: ./arch/node/types/anoma_config.juvix.md
                  - Anoma Environment: ./arch/node/types/anoma_environment.juvix.md
          - Hardware Component:
              - Local Key Value Storage Engine:
                  - Local Key Value Storage Engine: ./arch/node/engines/local_key_value_storage.juvix.md
                  - Local Key Value Storage Messages: ./arch/node/engines/local_key_value_storage_messages.juvix.md
                  - Local Key Value Storage Configuration: ./arch/node/engines/local_key_value_storage_config.juvix.md
                  - Local Key Value Storage Environment: ./arch/node/engines/local_key_value_storage_environment.juvix.md
                  - Local Key Value Storage Behaviour: ./arch/node/engines/local_key_value_storage_behaviour.juvix.md
              - Local Time Series Storage Engine:
                  - Local Time Series Storage Engine: ./arch/node/engines/local_time_series_storage.juvix.md
                  - Local Time Series Storage Messages: ./arch/node/engines/local_time_series_storage_messages.juvix.md
                  - Local Time Series Storage Configuration: ./arch/node/engines/local_time_series_storage_config.juvix.md
                  - Local Time Series Storage Environment: ./arch/node/engines/local_time_series_storage_environment.juvix.md
                  - Local Time Series Storage Behaviour: ./arch/node/engines/local_time_series_storage_behaviour.juvix.md
              - Logging Engine:
                  - Logging Engine: ./arch/node/engines/logging.juvix.md
                  - Logging Messages: ./arch/node/engines/logging_messages.juvix.md
                  - Logging Configuration: ./arch/node/engines/logging_config.juvix.md
                  - Logging Environment: ./arch/node/engines/logging_environment.juvix.md
                  - Logging Behaviour: ./arch/node/engines/logging_behaviour.juvix.md
              - Wall Clock Engine:
                  - Wall Clock Engine: ./arch/node/engines/wall_clock.juvix.md
                  - Wall Clock Messages: ./arch/node/engines/wall_clock_messages.juvix.md
                  - Wall Clock Configuration: ./arch/node/engines/wall_clock_config.juvix.md
                  - Wall Clock Environment: ./arch/node/engines/wall_clock_environment.juvix.md
                  - Wall Clock Behaviour: ./arch/node/engines/wall_clock_behaviour.juvix.md
          - Identity Component:
              - Identity Management Engine:
                  - Identity Management Engine: ./arch/node/engines/identity_management.juvix.md
                  - Identity Management Messages: ./arch/node/engines/identity_management_messages.juvix.md
                  - Identity Management Configuration: ./arch/node/engines/identity_management_config.juvix.md
                  - Identity Management Environment: ./arch/node/engines/identity_management_environment.juvix.md
                  - Identity Management Behaviour: ./arch/node/engines/identity_management_behaviour.juvix.md
              - Encryption Engine:
                  - Encryption Engine: ./arch/node/engines/encryption.juvix.md
                  - Encryption Messages: ./arch/node/engines/encryption_messages.juvix.md
                  - Encryption Configuration: ./arch/node/engines/encryption_config.juvix.md
                  - Encryption Environment: ./arch/node/engines/encryption_environment.juvix.md
                  - Encryption Behaviour: ./arch/node/engines/encryption_behaviour.juvix.md
              - Decryption Engine:
                  - Decryption Engine: ./arch/node/engines/decryption.juvix.md
                  - Decryption Messages: ./arch/node/engines/decryption_messages.juvix.md
                  - Decryption Configuration: ./arch/node/engines/decryption_config.juvix.md
                  - Decryption Environment: ./arch/node/engines/decryption_environment.juvix.md
                  - Decryption Behaviour: ./arch/node/engines/decryption_behaviour.juvix.md
              - Commitment Engine:
                  - Commitment Engine: ./arch/node/engines/commitment.juvix.md
                  - Commitment Messages: ./arch/node/engines/commitment_messages.juvix.md
                  - Commitment Configuration: ./arch/node/engines/commitment_config.juvix.md
                  - Commitment Environment: ./arch/node/engines/commitment_environment.juvix.md
                  - Commitment Behaviour: ./arch/node/engines/commitment_behaviour.juvix.md
              - Verification Engine:
                  - Verification Engine: ./arch/node/engines/verification.juvix.md
                  - Verification Messages: ./arch/node/engines/verification_messages.juvix.md
                  - Verification Configuration: ./arch/node/engines/verification_config.juvix.md
                  - Verification Environment: ./arch/node/engines/verification_environment.juvix.md
                  - Verification Behaviour: ./arch/node/engines/verification_behaviour.juvix.md
              - Reads For Engine:
                  - Reads For Engine: ./arch/node/engines/reads_for.juvix.md
                  - Reads For Messages: ./arch/node/engines/reads_for_messages.juvix.md
                  - Reads For Configuration: ./arch/node/engines/reads_for_config.juvix.md
                  - Reads For Environment: ./arch/node/engines/reads_for_environment.juvix.md
                  - Reads For Behaviour: ./arch/node/engines/reads_for_behaviour.juvix.md
              - Signs For Engine:
                  - Signs For Engine: ./arch/node/engines/signs_for.juvix.md
                  - Signs For Messages: ./arch/node/engines/signs_for_messages.juvix.md
                  - Signs For Configuration: ./arch/node/engines/signs_for_config.juvix.md
                  - Signs For Environment: ./arch/node/engines/signs_for_environment.juvix.md
                  - Signs For Behaviour: ./arch/node/engines/signs_for_behaviour.juvix.md
              - Naming Engine:
                  - Naming Engine: ./arch/node/engines/naming.juvix.md
                  - Naming Messages: ./arch/node/engines/naming_messages.juvix.md
                  - Naming Configuration: ./arch/node/engines/naming_config.juvix.md
                  - Naming Environment: ./arch/node/engines/naming_environment.juvix.md
                  - Naming Behaviour: ./arch/node/engines/naming_behaviour.juvix.md
  - Quick links: ./indexes/links.md
  - Juvix modules:
      - Prelude: ./prelude.juvix.md
      - Module Index: ./indexes/juvix_modules.md
  - Tutorials for contributors:
      - ./tutorial/index.md
      - Prepare working environment: ./tutorial/install/index.md
      - Use Git and GitHub: ./tutorial/branch.md
      - Updating the changelog: ./tutorial/changelog.md
      - Versioning: ./tutorial/versioning.md
      - File naming conventions: ./tutorial/file_naming.md
      - Write Markdown: ./tutorial/md/index.md
      - Headers and other Markdown formatting conventions: ./tutorial/md/headers_and_other_conventions.md
      - Use Wiki style links: ./tutorial/md/links.md
      - Include images in Markdown: ./tutorial/md/images.md
      - Include code snippets: ./tutorial/md/snippets.md
      - Add Juvix code for specification: ./tutorial/juvix.md
      - Add pending tasks with Todos admonition: ./tutorial/md/todos.md
      - Add literature references: ./tutorial/md/citations.md
      - Add diffs for versioning: ./tutorial/differ/index.md
      - Run pre commit checks: ./tutorial/commit_checks.md
      - Engines in Anoma:
          - ./tutorial/engines/index.md
          - Engine writing conventions: ./tutorial/engines/writing_conventions.md
          - Examples:
              - Template Engine:
                  - Template Engine: ./arch/node/engines/template.juvix.md
                  - Template Messages: ./arch/node/engines/template_messages.juvix.md
                  - Template Configuration: ./arch/node/engines/template_config.juvix.md
                  - Template Environment: ./arch/node/engines/template_environment.juvix.md
                  - Template Behaviour: ./arch/node/engines/template_behaviour.juvix.md
              - Ticker Engine:
                  - Ticker Engine: ./arch/node/engines/ticker.juvix.md
                  - Ticker Messages: ./arch/node/engines/ticker_messages.juvix.md
                  - Ticker Configuration: ./arch/node/engines/ticker_config.juvix.md
                  - Ticker Environment: ./arch/node/engines/ticker_environment.juvix.md
                  - Ticker Behaviour: ./arch/node/engines/ticker_behaviour.juvix.md
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/anoma
    - icon: fontawesome/brands/github
      link: https://github.com/anoma
    - icon: fontawesome/solid/blog
      link: https://anoma.net/blog
    - icon: fontawesome/brands/discourse
      link: https://research.anoma.net
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/anoma
    - icon: material/email
      link: mailto:arts@heliax.dev
  generator: false
  version: 1.0
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: overrides
  language: en
  google_analytics: G-WJWZWB2TW5
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Open Sans
    code: Fira Code
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.suggest
    - search.sharing
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.prune
    - navigation.indexes
    # - navigation.top
    - navigation.path
    - toc.follow
    - toc.integrate
plugins:
  - search
  - glightbox
  - juvix # Provided with mkdocs-juvix-plugin
  - todos
  - kroki: # docs: https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#readme
      ServerURL: !ENV [KROKI_SERVER_URL, 'https://kroki.io']
      FileTypes:
        - svg
        - png
      FileTypeOverrides:
        mermaid: svg
  - bibtex:
      bib_dir: "docs/references"
  - macros:
      verbose: false
      module_name: macros
      j2_block_start_string: "{@@"
      j2_block_end_string: "@@}"
      j2_variable_start_string: "{@"
      j2_variable_end_string: "@}"
hooks:
  - hooks/fix_changelog.py
exclude_docs: |
  **/.hooks/**
  docs/.juvix-build/**
  **/art-template/**/*.md
  */**/.juvix-build/
  docs/indexes/*.txt
  docs/indexes/*.dot
  docs/images/*.dot.svg
extra_css:
  - assets/css/juvix-material-style.css
  - assets/css/juvix-highlighting.css
  - assets/css/juvix_codeblock_footer.css
extra_javascript:
  - assets/js/extra.js
  - assets/js/highlight.js
  - assets/js/mathjax.js
  - assets/js/tex-svg-full.js
# See https://squidfunk.github.io/mkdocs-material/reference/math/?h=katex#comparing-mathjax-and-katex on why we use MathJax
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __ispan
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
validation:
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore
