site_name: !ENV [SITE_NAME, "Anoma specs"]
site_author: !ENV [SITE_AUTHOR, "Anoma Foundation"]
site_description: !ENV [SITE_DESCRIPTION, "The Anoma specs is a collection of documents that describe the architecture, design, and implementation of the Anoma Network."]
site_dir: !ENV [SITE_DIR, site]
site_url: !ENV [SITE_URL, 'https://specs.anoma.net/latest/']
site_version: !ENV [SITE_VERSION, "v0.2.0"]
copyright: !ENV [COPYRIGHT, "&copy; 2025 <a href=\"https://anoma.net\">Anoma Foundation</a>"]
repo_url: https://github.com/anoma/nspec
repo_name: anoma/nspec
edit_uri: edit/main/docs/
use_directory_urls: false
nav:
  - Home: index.md
  - Anoma architecture: ./arch/overview.md
  - Changelog: ./changelog.md
  - Indexes:
      - List of tags: ./indexes/tags.md
      - List of modules: ./indexes/modules.md
  - System architecture:
      - Identity Architecture:
          - Identity Architecture Types: ./arch/system/identity/identity.juvix.md
      - State Architecture:
          - Resource Machine:
              - ./arch/system/state/resource_machine/index.juvix.md
              - Primitive interfaces:
                  - ./arch/system/state/resource_machine/primitive_interfaces/index.juvix.md
                  - Set:
                      - Set interface: ./arch/system/state/resource_machine/primitive_interfaces/set.juvix.md
                      - Ordered set: ./arch/system/state/resource_machine/primitive_interfaces/ordered_set.juvix.md
                  - Map: ./arch/system/state/resource_machine/primitive_interfaces/map.juvix.md
                  - Fixed size type:
                      - Interface: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/fixed_size_type.juvix.md
                      - Arithmetic: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/arithmetic.juvix.md
                      - Hash: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/hash.juvix.md
                      - Delta hash: ./arch/system/state/resource_machine/primitive_interfaces/fixed_size_type/delta_hash.juvix.md
                  - Proving system:
                      - ./arch/system/state/resource_machine/primitive_interfaces/proving_system/index.md
                      - Definitions: ./arch/system/state/resource_machine/primitive_interfaces/proving_system/proving_system_types.juvix.md
                      - Delta proving system: ./arch/system/state/resource_machine/primitive_interfaces/proving_system/proving_system_delta.juvix.md
                  - Commitment accumulator: ./arch/system/state/resource_machine/primitive_interfaces/commitment_accumulator.juvix.md
                  - Nullifier set: ./arch/system/state/resource_machine/primitive_interfaces/nullifier_set.juvix.md
              - Data structures:
                  - Resource:
                      - ./arch/system/state/resource_machine/data_structures/resource/index.juvix.md
                      - Computable components:
                          - ./arch/system/state/resource_machine/data_structures/resource/computable_components/introduction.juvix.md
                          - Commitment: ./arch/system/state/resource_machine/data_structures/resource/computable_components/resource_commitment.juvix.md
                          - Nullifier: ./arch/system/state/resource_machine/data_structures/resource/computable_components/nullifier.juvix.md
                          - Kind: ./arch/system/state/resource_machine/data_structures/resource/computable_components/kind.juvix.md
                          - Delta: ./arch/system/state/resource_machine/data_structures/resource/computable_components/delta.juvix.md
                  - Compliance unit:
                      - Compliance unit: ./arch/system/state/resource_machine/data_structures/compliance_unit/compliance_unit.juvix.md
                      - Compliance proof: ./arch/system/state/resource_machine/data_structures/compliance_unit/compliance_proof.juvix.md
                  - Action:
                      - Action: ./arch/system/state/resource_machine/data_structures/action/index.juvix.md
                      - Resource logic proof: ./arch/system/state/resource_machine/data_structures/action/resource_logic_proof.juvix.md
                  - Transaction:
                      - Transaction: ./arch/system/state/resource_machine/data_structures/transaction/transaction.juvix.md
                      - Delta proof: ./arch/system/state/resource_machine/data_structures/transaction/delta_proof.juvix.md
                      - Transaction Function: ./arch/system/state/resource_machine/data_structures/transaction/transaction_function.juvix.md
                      - Transaction With Payment: ./arch/system/state/resource_machine/data_structures/transaction/transaction_with_payment.juvix.md
              - Execution flow: ./arch/system/state/resource_machine/execution_flow/flow.juvix.md
              - Notes:
                  - Roles and requirements: ./arch/system/state/resource_machine/notes/roles_and_requirements.juvix.md
                  - Stored data format: ./arch/system/state/resource_machine/notes/storage.juvix.md
                  - Function formats:
                      - Transaction function format: ./arch/system/state/resource_machine/notes/function_formats/transaction_function_format.juvix.md
                  - Applications: ./arch/system/state/resource_machine/notes/applications.juvix.md
                  - Runnable trait: ./arch/system/state/resource_machine/notes/runnable.juvix.md
                  - Nockma implementation: ./arch/system/state/resource_machine/notes/nockma.juvix.md
                  - Nockma runnable: ./arch/system/state/resource_machine/notes/nockma_runnable.juvix.md
  - Integrations:
      - Protocol Adapters:
          - ./arch/integrations/adapters/index.md
          - Ethereum Virtual Machine: ./arch/integrations/adapters/evm.md
  - Tutorials:
      - Contributor guidelines:
          - Global principles and guidelines: ./tutorial/principles_and_guidelines.md
          - Prepare working environment: ./tutorial/install/index.md
          - Add Juvix code for specification: ./tutorial/juvix.md
          - Write Markdown: ./tutorial/md/index.md
          - Headers and other Markdown formatting conventions: ./tutorial/md/headers_and_other_conventions.md
          - Use Wiki style links: ./tutorial/md/links.md
          - Include images in Markdown: ./tutorial/md/images.md
          - Include code snippets: ./tutorial/md/snippets.md
          - Add pending tasks with Todos admonition: ./tutorial/md/todos.md
          - Add literature references: ./tutorial/md/citations.md
          - Use Git and GitHub: ./tutorial/branch.md
          - File naming conventions: ./tutorial/file_naming.md
          - Run pre commit checks: ./tutorial/commit_checks.md
          - Updating the changelog: ./tutorial/changelog.md
          - Versioning: ./tutorial/versioning.md
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/anoma
    - icon: fontawesome/brands/github
      link: https://github.com/anoma
    - icon: fontawesome/solid/blog
      link: https://anoma.net/blog
    - icon: fontawesome/brands/discourse
      link: https://research.anoma.net
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/anoma
    - icon: material/email
      link: mailto:arts@heliax.dev
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: overrides
  language: en
  google_analytics: G-WJWZWB2TW5
  icon:
    edit: material/file-edit
    view: material/language-markdown
    repo: fontawesome/brands/github
    search: octicons/search-16
    previous: octicons/arrow-left-16
    next: octicons/arrow-right-16
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.suggest
    - search.sharing
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    # - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - navigation.path
    - toc.follow
    # - toc.integrate
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox
  - juvix # Provided with mkdocs-juvix-plugin
  - todos
  - kroki: # docs: https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#readme
      ServerURL: !ENV [KROKI_SERVER_URL, 'https://kroki.io']
      FileTypes:
        - svg
        - png
      FileTypeOverrides:
        mermaid: svg
  - drawio
  - tags:
      tags_file: indexes/tags.md
  - bibtex:
      bib_dir: "docs/references"
  - macros:
      verbose: false
      module_name: macros
      j2_block_start_string: "{@@"
      j2_block_end_string: "@@}"
      j2_variable_start_string: "{@"
      j2_variable_end_string: "@}"
watch:
  - docs/assets/css/extra.css
exclude_docs: |
  **/.hooks/**
  docs/.juvix-build/**
  **/art-template/**/*.md
  */**/.juvix-build/
  docs/indexes/*.txt
  docs/indexes/*.dot
  docs/images/*.dot.svg
extra_css:
  - assets/css/juvix-material-style.css
  - assets/css/juvix-highlighting.css
  - assets/css/juvix_codeblock_footer.css
  - assets/css/latte-light.css
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
  - assets/js/highlight.js
  - assets/js/mathjax.js
  - assets/js/tex-svg-full.js
# See https://squidfunk.github.io/mkdocs-material/reference/math/?h=katex#comparing-mathjax-and-katex on why we use MathJax
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __ispan
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
validation:
  nav:
    omitted_files: ignore
    not_found: warn
    absolute_links: ignore
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: warn
