[tool.poetry]
name = "nspec"
package-mode = false
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4"
mkdocs-material = {extras = ["imaging"], version = "^9.5.41"}
mkdocs-juvix-plugin = {path = "/Users/jonaprieto/anoma/juvix-mkdocs", develop = true}
graphviz = "^0.20.3"
pymdown-extensions = "^10.11.2"
mkdocs-macros-plugin = "^1.3.6"
mkdocs-kroki-plugin = "^0.9.0"
mkdocs-glightbox = "^0.4.0"
mkdocs-bibtex = "^2.16.2"
# extra plugins not essential
mkdocs-git-authors-plugin = "^0.9.0"
mkdocs-git-committers-plugin-2 = "^2.3.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.9"
mkdocs-git-revision-date-plugin = "^0.3.2"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
