[tool.poetry]
package-mode = false
name = "nspec"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.6.0"
mkdocs-bibtex = "^2.16.0"
mkdocs-git-authors-plugin = "^0.9.0"
mkdocs-git-committers-plugin-2 = "^2.3.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.6"
mkdocs-git-revision-date-plugin = "^0.3.2"
mkdocs-literate-nav = "^0.6.1"
mkdocs-macros-plugin = "^1.0.5"
mkdocs-material = {extras = ["imaging"], version = "^9.5.25"}
mkdocs-section-index = "^0.3.9"
pymdown-extensions = "^10.8.1"
mkdocs-ezglossary-plugin = "^1.6.10"
mkdocs-autorefs = "^1.0.1"
mkdocs-glightbox = "^0.4.0"
mkdocs-juvix-plugin = "^0.2.7"
mike = "^2.1.1"
pre-commit = "^3.7.1"
python-levenshtein = "^0.25.1"
fuzzywuzzy = "^0.18.0"
common = {path = "hooks"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
