@startmindmap

+ **Transaction**
++ computed by transaction function
+++_ needs to be run by the executor
+++_ executable on the [[https://specs.anoma.net/v0.1.4/arch/system/state/resource_machine/primitive_interfaces/transaction_function_vm.html?h=function Transaction function VM]]
+++_ produces ""transaction"" as a result
++ some kind of //"code"//
+++[#white] **TODO** specifically/examples?

-- verification\n(via proving systems)
---_ compute ""verify"" operation
---_ check gas
---_ [[https://specs.anoma.net/v0.1.4/arch/system/state/resource_machine/primitive_interfaces/transaction_function_vm.html?h=function → Transaction function VM]]
-- //"execution"//\n
--- perform reads an writes
---- transaction function computation
---- transaction //"execution"//
---[#white] **TODO** other side effects ???

@endmindmap
