[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "common"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ['mkdocs', 'click']

[project.scripts]
todos = "common:cli.todos.main"
