
name: anoma-spec-ci
'on':
  push:
    branches:
      - main
  schedule:
    - cron: 0 2 * * *

  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: "Docs build type"
        default: dev
        options:
          - dev
          - latest

  pull_request:
    branches:
      - main
      - 'v**'
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - closed

env:
  CI: true
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INSIDERS_TOKEN: ${{ secrets.INSIDERS_TOKEN }}
  GIT_COMMITTER_EMAIL: arts@heliax.dev
  GIT_COMMITTER_NAME: Anoma Research
  REPORT_BROKEN_WIKILINKS: true
  JUVIX_ENABLED: true
  DIFF_ENABLED: true
  IMAGES_ENABLED: true
  USE_DOT: true
  VERSION_SELECTOR: ${{ github.event_name != 'pull_request' }}

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config --global user.name arts
          git config --global user.email arts@heliax.dev

      - name: comment on PR (Pull Request)
        if: >-
          github.event_name == 'pull_request'
        run: gh $GH_FLAGS --edit-last --body "$MSG" || gh $GH_FLAGS --body "$MSG" || true
        env:
          MSG: "The build is in progress. Please wait for the preview link."
          GH_FLAGS: pr -R anoma/nspec comment ${{ github.event.pull_request.number }}

      - name: Download latest nightly Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: anoma/juvix-nightly-builds
          cache: enable
          rename-to: juvix
          chmod: 0755

      - uses: actions/cache@v3
        with:
          key: juvix-cache-${{ hashFiles('**/*.juvix.md') }}-${{ hashFiles('**/*.juvix') }}
          path: .juvix-build
          restore-keys: |
            juvix-cache-

      - id: juvix-version
        name: See the dev version in the documentation
        run: |
          juvix --version

      - name: typecheck Juvix code
        run: |
          juvix typecheck docs/everything.juvix.md || true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')-${{ hashFiles( '**/requirements.txt' )}}-${{ hashFiles( '**/*.py' )}}" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Linux dependencies
        run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant graphviz

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Hooks cache
        uses: actions/cache@v3
        with:
          key: hooks-${{ env.cache_id }}
          path: .hooks
          restore-keys: |
            hooks-

      - name: Build MkDocs (Pull Request)
        if: >-
          github.event_name == 'pull_request'
        run: |
          mkdocs build --clean --config-file mkdocs.yml --site-dir $SITE_DIR
        env:
          SITE_DIR: pull-${{ github.event.pull_request.number }}
          SITE_URL: https://anoma.github.io/nspec/pull-${{ github.event.pull_request.number }}

      - name: comment on PR (Pull Request)
        if: failure() && github.event_name == 'pull_request'
        run: |
          gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "The build failed. Please check the logs." || true

      - name: Install MkDocs Insiders
        run: |
          pip install git+https://${INSIDERS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Test Build MkDocs Insiders (Pull Request)
        if: github.event_name == 'pull_request'
        id: test-build-mkdocs-insiders
        run: |
          mkdocs build --clean --config-file mkdocs.insiders.yml --site-dir $SITE_DIR
        env:
          SITE_DIR: pull-${{ github.event.pull_request.number }}
          SITE_URL: https://anoma.github.io/nspec/pull-${{ github.event.pull_request.number }}

      - name: The build failed with MkDocs Insiders comment (Pull Request)
        if: github.even_name == 'pull_request' && steps.test-build-mkdocs-insiders.outcome == 'failure'
        run: |
          gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "The build failed with MkDocs Insiders. Please check the logs." || true

      - name: Cat aliases and juvix_modules
        if: github.event_name == 'pull_request'
        run: |
          cat .hooks/aliases.json
          cat .hooks/juvix_modules.json

      - name: Deploy Preview comment (Pull Request)
        if: github.event_name == 'pull_request' &&
            steps.test-build-mkdocs-insiders.outcome == 'success'
        run: |
          gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "Basic build successful and build with MkDocs Insiders successful. We are now deploying the preview." || true

      - name: Build tutorial (Pull Request)
        id: build-tutorial-pull
        if: >-
          github.event_name == 'pull_request'
        run: |
          mkdocs build --clean --config-file tutorial.yml --site-dir $SITE_DIR
        env:
          SITE_DIR: pull-${{ github.event.pull_request.number }}/tutorial
          SITE_URL:  https://anoma.github.io/nspec/pull-${{ github.event.pull_request.number }}/tutorial/

      - name: Deploy Preview (Pull Request)
        if: github.event_name == 'pull_request' && success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: pull-${{ github.event.pull_request.number }}
          target-folder: pull-${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false

      - name: Report PR preview link (Pull Request)
        if: >-
           github.event_name == 'pull_request' && success()
        run: gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "$MSG" || true
        env:
          MSG: "Success! The preview of this PR will be available at https://anoma.github.io/nspec/pull-${{ github.event.pull_request.number }}/ in a few minutes.\n\nPlease note that this link will be deleted when the PR is closed or merged."

      - name: Failed preview build comment (Pull Request)
        if: >-
          github.event_name == 'pull_request' && failure()
        run: |
          gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "The preview of this PR failed to build. Please check the logs." || true

      - name: Delete the PR preview if the PR is closed or merged (Pull Request)
        if: github.event_name == 'pull_request' && (github.event.pull_request.merged == true || github.event.action == 'closed')
        run: |
          git checkout gh-pages
          if [-d "pull-${{ github.event.pull_request.number }}"]; then
            rm -rf "pull-${{ github.event.pull_request.number }}"
            git add .
            git commit -m "Delete preview for PR #${{ github.event.pull_request.number }}"
            git push
          fi
          gh pr -R anoma/nspec comment ${{ github.event.pull_request.number }} --edit-last --body "The preview of this PR has been deleted." || true

      # -------------------------------------------------------------

      - name: Run MkDocs Insiders (Main branch Workflow Dispatch)
        if: >-
          github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          MKDOCSCONFIG=mkdocs.insiders.yml make ${{ github.event.inputs.build-type }}

      - name: Run MkDocs Insiders (Main branch - Push)
        if: >-
          github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
        run: |
          MKDOCSCONFIG=mkdocs.insiders.yml make dev
        env:
          SITE_DIR: dev
          SITE_URL: https://anoma.github.io/nspec/dev/

      - name: Build tutorial
        run: |
          mkdocs build --clean --config-file tutorial.yml --site-dir $SITE_DIR
        if: >-
          github.ref == 'refs/heads/main'
        env:
          SITE_DIR: tutorial
          SITE_URL: https://anoma.github.io/nspec/tutorial/

      - name: Deploy Preview (Main branch)
        if : >-
          github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: tutorial
          target-folder: tutorial
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false