
'on': 
  push:
    branches:
      - v*

env:
  CI: true
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INSIDERS_TOKEN: ${{ secrets.INSIDERS_TOKEN }}
  GIT_COMMITTER_EMAIL: arts@heliax.dev
  GIT_COMMITTER_NAME: Anoma Research

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - run: |
          git config --global user.name '$GIT_COMMITTER_NAME'
          git config --global user.email '$GIT_COMMITTER_EMAIL'

      - name: comment on PR
        run: gh $GH_FLAGS --edit-last --body "$MSG" || gh $GH_FLAGS --body "$MSG" || true
        env:
          MSG: "The build is in progress. Please wait for the preview link."
          GH_FLAGS: pr -R anoma/nspec comment ${{ github.event.pull_request.number }}

      - name: Download latest nightly Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: anoma/juvix-nightly-builds
          cache: enable
          rename-to: juvix
          chmod: 0755

      - uses: actions/cache@v3
        with:
          key: juvix-cache-${{ hashFiles('**/*.juvix.md') }}-${{ hashFiles('**/*.juvix') }}
          path: .juvix-build
          restore-keys: |
            juvix-cache-

      - name: Typecheck everything.juvix.md
        run: |
          juvix --version
          juvix typecheck docs/everything.juvix.md || true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')-${{ hashFiles( '**/requirements.txt' )}}-${{ hashFiles( '**/*.py' )}}" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Hooks cache
        uses: actions/cache@v3
        with:
          key: hooks-${{ env.cache_id }}
          path: .hooks
          restore-keys: |
            hooks-

      - run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant graphviz
      - run: pip install -r requirements.txt

      - name: Build MkDocs with material insiders version
        id: material
        run: |
          pip install git+https://${INSIDERS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          mkdocs build --clean --config-file mkdocs.insiders.yml --site-dir $SITE_DIR
        env:
          SITE_DIR: latest
          SITE_URL: https://anoma.github.io/nspec/latest/

      - if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './site'
          target_folder: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
          git-config-name: $GIT_COMMITTER_NAME
          git-config-email: $GIT_COMMITTER_EMAIL
