name: deploy
'on':
  push:
    branches:
      - v*
env:
  CI: true
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INSIDERS_TOKEN: ${{ secrets.INSIDERS_TOKEN }}
  PYTHON_VERSION: 3.x
  POETRY_VERSION: 1.8.3
  # NOTE: insiders version must correspond to the mkdocs-material version in pyproject.toml
  #       and must be updated in all .yml files in this directory
  INSIDERS_VERSION: 9.5.37-insiders-4.53.13
  GIT_COMMITTER_EMAIL: arts@heliax.dev
  GIT_COMMITTER_NAME: Anoma Research
  REPORT_TODOS: false
  SHOW_TODOS_IN_MD: false
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git config --global user.name 'Anoma Research'
          git config --global user.email 'arts@heliax.dev'
      - name: comment on PR
        run: gh $GH_FLAGS --edit-last --body "$MSG" || gh $GH_FLAGS --body "$MSG" || true
        env:
          MSG: "The build is in progress. Please wait for the preview link."
          GH_FLAGS: pr -R anoma/nspec comment ${{ github.event.pull_request.number }}
      - name: Install the right Juvix for the Specs
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix
          tag: v0.6.6
          cache: enable
          rename-to: juvix
          chmod: 0755
      - uses: actions/cache@v3
        with:
          key: juvix-cache-${{ hashFiles('**/*.juvix.md') }}-${{ hashFiles('**/*.juvix') }}
          path: .juvix-build
          restore-keys: |
            juvix-cache-
      - name: Typecheck everything.juvix.md
        run: |
          juvix --version
          juvix typecheck docs/everything.juvix.md || true
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - run: echo "cache_id=$(date --utc '+%V')-${{ hashFiles( '**/poetry.lock' )}}-${{ hashFiles( '**/*.py' )}}" >> $GITHUB_ENV
      - name: Cache .venv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ env.cache_id }}
      - name: Cache .cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Cache .hooks
        uses: actions/cache@v3
        with:
          key: hooks-${{ env.cache_id }}
          path: .hooks
          restore-keys: |
            hooks-
      - name: Install Linux dependencies
        run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant graphviz
      - name: Install Python dependencies
        run: poetry install
      - name: Build MkDocs with material insiders version
        id: material
        run: |
          pip install git+https://${INSIDERS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@${INSIDERS_VERSION}
          poetry run mkdocs build --clean --config-file mkdocs.insiders.yml --site-dir $SITE_DIR
        env:
          SITE_DIR: ${{ env.BRANCH_NAME }}
          SITE_URL: https://anoma.github.io/nspec/${{ env.BRANCH_NAME }}
      - if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.BRANCH_NAME }}
          target-folder: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
          git-config-name: Anoma Research
          git-config-email: arts@heliax.dev
      - name: get latest version from VERSION file
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - if: ${{ env.BRANCH_NAME == steps.version.outputs.version }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.BRANCH_NAME }}
          target-folder: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
          git-config-name: Anoma Research
          git-config-email:
