name: update-version-selector

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove versions starting with "pull"
        run: |
          jq 'map(select(.version | startswith("pull") | not))' versions.json > temp.json && mv temp.json versions.json
        shell: bash

      - name: Commit and push changes if there are changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add versions.json
          # Check if there are any changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Remove versions starting with 'pull'"
            git push
          fi

